image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - yarn global add node-gyp
  - yarn --version

build:
  stage: build
  tags:
    - ci
  script:
    - echo "This job builds something..."

code-quality:
  stage: test
  tags:
    - ci
  script:
    - yarn install
    - yarn lint

# unit-test:
#   services:
#     - name: mongo:latest
#   stage: test
#   tags:
#     - ci
#   before_script: []
#   script:
#     - yarn install
#     - NODE_ENV=test MONGO_SERVERS=mongodb://mongo:27017/test yarn test

deploy:
  stage: deploy
  tags:
    - ci
  script:
    - echo "This job deploy something..."
